/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module main (
  input A,
  input B,
  input C,
  input D,
  output P
);
  assign P = ~ ((A ^ B) ^ (C ^ D));
endmodule
