/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module main (
  input A,
  input B,
  input Cin,
  output Cout,
  output S
);
  wire s0;
  assign s0 = (A ^ B);
  assign S = (s0 ^ Cin);
  assign Cout = ((Cin & s0) | (B & A));
endmodule
