/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module main (
  input OB,
  input CLK,
  input RST,
  output RR,
  output RL
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire RL_temp;
  wire s4;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( 1'b0 ),
    .D( OB ),
    .C( CLK ),
    .Clr( RST ),
    .Q( s3 ),
    .\~Q ( s1 )
  );
  assign RL_temp = (s2 & s3);
  assign RR = (s0 & s3);
  assign s4 = ((OB & s0 & s1) | (~ OB & s2) | RL_temp);
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( 1'b0 ),
    .D( s4 ),
    .C( CLK ),
    .Clr( RST ),
    .Q( s2 ),
    .\~Q ( s0 )
  );
  assign RL = RL_temp;
endmodule
