/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module main (
  input I0,
  input I1,
  output O0,
  output O1,
  output O2,
  output O3
);
  wire s0;
  wire s1;
  assign O3 = (I1 & I0);
  assign s0 = ~ I0;
  assign s1 = ~ I1;
  assign O0 = (s0 & s1);
  assign O1 = (I0 & s1);
  assign O2 = (s0 & I1);
endmodule
