/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module main (
  input A,
  input B,
  input Cin,
  input A1,
  input B1,
  input A2,
  input B2,
  input A3,
  input B3,
  input A4,
  input B4,
  input A5,
  input B5,
  input A6,
  input B6,
  input A7,
  input B7,
  output S,
  output S1,
  output S2,
  output S3,
  output S4,
  output S5,
  output S6,
  output CoutFinal,
  output S7
);
  wire s0;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  assign s0 = (A ^ B);
  assign s9 = (A1 ^ B1);
  assign s11 = (A2 ^ B2);
  assign s13 = (A3 ^ B3);
  assign s15 = (A4 ^ B4);
  assign s17 = (A5 ^ B5);
  assign s19 = (A6 ^ B6);
  assign s21 = (A7 ^ B7);
  assign S = (s0 ^ Cin);
  assign s8 = ((Cin & s0) | (B & A));
  assign S1 = (s9 ^ s8);
  assign s10 = ((s8 & s9) | (B1 & A1));
  assign S2 = (s11 ^ s10);
  assign s12 = ((s10 & s11) | (B2 & A2));
  assign S3 = (s13 ^ s12);
  assign s14 = ((s12 & s13) | (B3 & A3));
  assign S4 = (s15 ^ s14);
  assign s16 = ((s14 & s15) | (B4 & A4));
  assign S5 = (s17 ^ s16);
  assign s18 = ((s16 & s17) | (B5 & A5));
  assign S6 = (s19 ^ s18);
  assign s20 = ((s18 & s19) | (B6 & A6));
  assign S7 = (s21 ^ s20);
  assign CoutFinal = ((s20 & s21) | (B7 & A7));
endmodule
